### ISSUE TITLE
Back Callback

### ISSUE THREAD

**Issue by CanadienFr** [FivemTools/ft_menuBuilder#1]
Il manque une fonction pour exécuter un Callback lorsqu'on back.
Peut-être je n'ai pas trouvé.

PS: il est génial ton menu je suis entraîne de tous convertir mes addons avec ton menu 👍 .

**Comment by CanadienFr** [comment]
Je crois que j'ai trouvé.

**Comment by CanadienFr** [comment]
OMG C'est de la tuerie tes scripts. 
J'ai trouvé ce que je recherchais.

**Comment by samuelds** [comment]
Pour les gens qui cherchent comment faire c'est dans settings et puis back.
Je vais bientôt ajout la possibilité d'utiliser directement des events comme pour le exec et le hover

**Comment by CanadienFr** [comment]
J'ai une question est-ce que sa te dérange si je renomme le dossier  et les events ? 
Je laisse les crédits en haut et mes modifications seront jamais partager.

J'aime connaitre mes events par cœur.

**Comment by CanadienFr** [comment]
Si tu veux ajouter un léger+  c'est d'ajouter deux autres settings. Je l'ai faite sur ma version. c'est le texte scale, moi j'ai faite titlescale et btntextscale. Parce que  0.4 c'est trop fat pour moi :)

**Comment by samuelds** [comment]
Je n'ai pas envie que me code commence à avoir 5000 versions différentes, mais par contre je peux ajouter des options si besoin pour éviter que l'on modifie mon code. 

Et puis si l'on modifie mon code et que je le mets à jour sa casse toutes les modifications #essential, c'est pour cela que ft_menuBuilder est et doit rester une ressource à part entière. J'ai mis les exports car passé par des events utiliser de la bande passante (donc augmente le risque de desync).

Si ta une liste d'ajout que je peux faire hésite pas à proposer :)

**Comment by CanadienFr** [comment]
Je parlais pas spécialement de ce script. J'utilise actuellement tous tes scripts. Si tu fais des modifications je n'aurais aucun problèmes à les ajouter sur ma version. Sachant que tout les fichiers ne sortirons jamais de mon PC. Je respect ton choix je vais remettre tous met fichier en original.
